# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('startData', models.DateField()),
                ('endData', models.DateField()),
                ('comment', models.TextField(max_length=500)),
                ('partB', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=50)),
                ('masterID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('type', models.BooleanField()),
                ('mark', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('comment', models.TextField(max_length=200)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelContractDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=50)),
                ('deviceID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('partDevice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelPersonDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=50)),
                ('relatedPerson', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
            ],
            bases=('Rainbow_WEB.device',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
                ('speed', models.IntegerField()),
            ],
            bases=('Rainbow_WEB.device',),
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
                ('speed', models.IntegerField()),
                ('cap', models.IntegerField()),
            ],
            bases=('Rainbow_WEB.device',),
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
                ('addr', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
            ],
            bases=('Rainbow_WEB.device',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
                ('cap', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('slot', models.IntegerField()),
            ],
            bases=('Rainbow_WEB.device',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rainbow_WEB.Device')),
            ],
            bases=('Rainbow_WEB.device',),
        ),
    ]
